### ISSUE TITLE
Rename devtools-plugin to devtools

### ISSUE THREAD

**Issue by coffee-cup** [prodo-ai/prodo#108]
Our other plugins are not suffixed with `-plugin`. The `devtools-plugin` should be renamed to `devtools`. We should also probably deprecate the current devtools-plugin package on NPM (can we redirect packages?)

**Comment by andrejak** [comment]
I haven't seen the option to redirect (apart from leaving some documentation on it), but I doubt anyone has installed the devtools plugin except us, so deprecating is probably enough.
