### ISSUE TITLE
Devtools plugin dependencies issue

### ISSUE THREAD

**Issue by coffee-cup** [prodo-ai/prodo#109]
When installing the devtools in a repo non in the Prodo monorepo, there are issues with dependencies

- `@prodo/devtools-core` is not a dep of `@prodo/devtools-plugin` so you have to install it separatly
- After installing `@prodo/devtools-core` and `@prodo/devtools-plugin` I get a bunch of errors related to `react-editable-json-tree`

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/3044853/65623933-bed73300-dfc0-11e9-91bb-6f80ee126115.png">

**Comment by coffee-cup** [comment]
@andrejak I still seem to be getting issue. Should it be fixed in the latest version (0.0.10)?

**Comment by andrejak** [comment]
Yes, I wasn't seeing it in my project anymore. Are you talking about the devtools-core issue or the react-editable-json-tree?

**Comment by coffee-cup** [comment]
The react-editable-json-tree thing. It is in a project that is not in our monorepo.
