### ISSUE TITLE
Devtools & Plugin States

### ISSUE THREAD

**Issue by andrejak** [prodo-ai/prodo#118]
This is a general issue for what'll be relevant for several plugins. Currently, devtools only display "state". So if you're using the "local" plugin for example, there's no way for you to inspect "local" state, except it will show up in previous and next universe in the action log. 

We need to decide: should plugins have a way of adding panels to devtools? Or should devtools just show additional panels/features/functionality if they detect that a plugin is in use?

**Comment by coffee-cup** [comment]
I think the devtools could show multiple parts of the universe (possible in the same pane for now). When a plugin is created, the plugin author could _expose_ part of the universe to the devtools. It could look something like,

```ts
const myPlugin = createPlugin("myPlugin");

myPlugin.exposeUniverseVars("foo");
```

In this case, the devtools will show state (as always), and will also show `universe.foo`. This is what the local plugin will want to do, but the firestore plugin may not want to expose the `db_cache`.

**Comment by andrejak** [comment]
I like this idea. Do you want me to have a look at implementing it?

May help with https://github.com/prodo-ai/prodo/issues/159 (part of the problem is devtools doesn't detect route updates and doesn't think it needs to rerender)

**Comment by coffee-cup** [comment]
Sure, I think it would be really useful to have. There have been a few times where I wanted to see the `local` or `route` states in the devtools.

**Comment by andrejak** [comment]
Do you think that those exposed states should be editable in the State panel, or separate? That might be tricky to implement.  (eg changing the route will have to redirect the page)

**Comment by coffee-cup** [comment]
Hmm, thats a good point. Probably just read-only for now
