### ISSUE TITLE
async transpilation bug

### ISSUE THREAD

**Issue by Onurbon** [prodo-ai/prodo#53]
Input:

![image](https://user-images.githubusercontent.com/3934784/64790841-ab62ab80-d56e-11e9-83c1-d286d5735507.png)

Output: 

![image](https://user-images.githubusercontent.com/3934784/64790908-ca613d80-d56e-11e9-80e1-8a9818c2fa95.png)

Resulting console error: `Uncaught SyntaxError: await is only valid in async function`

**Comment by coffee-cup** [comment]
Closed by #54
