### ISSUE TITLE
source mapping not working

### ISSUE THREAD

**Issue by Onurbon** [prodo-ai/prodo#62]
Sometime the sourcemaps produced by Parcel (when using prodo/babel-plugin) work only on Firefox but not on Chrome. Sometimes, we don't get source maps on Firefox either.

Steps to reproduce:

Checkout `5ce46c976a576acf2b6483bb864803d672c500ef` (from the branch `f/test-kanban`) and run `yarn start` from `example/kanban`. 

Screenshot: 
![image](https://user-images.githubusercontent.com/3934784/64821954-d9b2ac00-d5ab-11e9-8d5d-7bdebaae25d4.png)

**Comment by tdawes** [comment]
Can you please add `"sourceMaps": "both"` to your _.babelrc_ and see if the problem goes away?

**Comment by coffee-cup** [comment]
This was fixed when we moved to webpack
